using System.Collections.Generic;
using Dynatrace.Net.Configuration.Services.Models;

namespace Dynatrace.Net.Common.Converters
{
	public class ConditionAttributeTypesConverter : JsonEnumConverter<ConditionAttributeTypes>
	{
		private static readonly Dictionary<ConditionAttributeTypes, string> s_pairs = new Dictionary<ConditionAttributeTypes, string>
		{
			[ConditionAttributeTypes.ActorSystem] = "ACTOR_SYSTEM",
			[ConditionAttributeTypes.AkkaActorClassName] = "AKKA_ACTOR_CLASS_NAME",
			[ConditionAttributeTypes.AkkaActorMessageType] = "AKKA_ACTOR_MESSAGE_TYPE",
			[ConditionAttributeTypes.AkkaActorPath] = "AKKA_ACTOR_PATH",
			[ConditionAttributeTypes.AzureFunctionsFunctionName] = "AZURE_FUNCTIONS_FUNCTION_NAME",
			[ConditionAttributeTypes.AzureFunctionsSiteName] = "AZURE_FUNCTIONS_SITE_NAME",
			[ConditionAttributeTypes.CicsProgramName] = "CICS_PROGRAM_NAME",
			[ConditionAttributeTypes.CicsSystemId] = "CICS_SYSTEM_ID",
			[ConditionAttributeTypes.CicsTaskId] = "CICS_TASK_ID",
			[ConditionAttributeTypes.CicsTransactionId] = "CICS_TRANSACTION_ID",
			[ConditionAttributeTypes.CicsUserId] = "CICS_USER_ID",
			[ConditionAttributeTypes.CpuTime] = "CPU_TIME",
			[ConditionAttributeTypes.CtgGatewayUrl] = "CTG_GATEWAY_URL",
			[ConditionAttributeTypes.CtgProgram] = "CTG_PROGRAM",
			[ConditionAttributeTypes.CtgServerName] = "CTG_SERVER_NAME",
			[ConditionAttributeTypes.CtgTransactionId] = "CTG_TRANSACTION_ID",
			[ConditionAttributeTypes.CustomserviceClass] = "CUSTOMSERVICE_CLASS",
			[ConditionAttributeTypes.CustomserviceMethod] = "CUSTOMSERVICE_METHOD",
			[ConditionAttributeTypes.DatabaseChildCallCount] = "DATABASE_CHILD_CALL_COUNT",
			[ConditionAttributeTypes.DatabaseChildCallTime] = "DATABASE_CHILD_CALL_TIME",
			[ConditionAttributeTypes.DatabaseHost] = "DATABASE_HOST",
			[ConditionAttributeTypes.DatabaseName] = "DATABASE_NAME",
			[ConditionAttributeTypes.DatabaseType] = "DATABASE_TYPE",
			[ConditionAttributeTypes.DatabaseUrl] = "DATABASE_URL",
			[ConditionAttributeTypes.DiskIoTime] = "DISK_IO_TIME",
			[ConditionAttributeTypes.ErrorCount] = "ERROR_COUNT",
			[ConditionAttributeTypes.EsbApplicationName] = "ESB_APPLICATION_NAME",
			[ConditionAttributeTypes.EsbInputType] = "ESB_INPUT_TYPE",
			[ConditionAttributeTypes.EsbLibraryName] = "ESB_LIBRARY_NAME",
			[ConditionAttributeTypes.EsbMessageFlowName] = "ESB_MESSAGE_FLOW_NAME",
			[ConditionAttributeTypes.ExceptionClass] = "EXCEPTION_CLASS",
			[ConditionAttributeTypes.ExceptionMessage] = "EXCEPTION_MESSAGE",
			[ConditionAttributeTypes.FailedState] = "FAILED_STATE",
			[ConditionAttributeTypes.FailureReason] = "FAILURE_REASON",
			[ConditionAttributeTypes.FlawState] = "FLAW_STATE",
			[ConditionAttributeTypes.HttpRequestMethod] = "HTTP_REQUEST_METHOD",
			[ConditionAttributeTypes.HttpStatus] = "HTTP_STATUS",
			[ConditionAttributeTypes.HttpStatusClass] = "HTTP_STATUS_CLASS",
			[ConditionAttributeTypes.ImsProgramName] = "IMS_PROGRAM_NAME",
			[ConditionAttributeTypes.ImsTransactionId] = "IMS_TRANSACTION_ID",
			[ConditionAttributeTypes.ImsUserId] = "IMS_USER_ID",
			[ConditionAttributeTypes.IoTime] = "IO_TIME",
			[ConditionAttributeTypes.LambdaColdstart] = "LAMBDA_COLDSTART",
			[ConditionAttributeTypes.LockTime] = "LOCK_TIME",
			[ConditionAttributeTypes.MessagingDestinationType] = "MESSAGING_DESTINATION_TYPE",
			[ConditionAttributeTypes.MessagingIsTemporaryQueue] = "MESSAGING_IS_TEMPORARY_QUEUE",
			[ConditionAttributeTypes.MessagingQueueName] = "MESSAGING_QUEUE_NAME",
			[ConditionAttributeTypes.MessagingQueueVendor] = "MESSAGING_QUEUE_VENDOR",
			[ConditionAttributeTypes.NetworkIoTime] = "NETWORK_IO_TIME",
			[ConditionAttributeTypes.NonDatabaseChildCallCount] = "NON_DATABASE_CHILD_CALL_COUNT",
			[ConditionAttributeTypes.NonDatabaseChildCallTime] = "NON_DATABASE_CHILD_CALL_TIME",
			[ConditionAttributeTypes.ProcessGroupName] = "PROCESS_GROUP_NAME",
			[ConditionAttributeTypes.ProcessGroupTag] = "PROCESS_GROUP_TAG",
			[ConditionAttributeTypes.RemoteEndpoint] = "REMOTE_ENDPOINT",
			[ConditionAttributeTypes.RemoteMethod] = "REMOTE_METHOD",
			[ConditionAttributeTypes.RemoteServiceName] = "REMOTE_SERVICE_NAME",
			[ConditionAttributeTypes.RequestName] = "REQUEST_NAME",
			[ConditionAttributeTypes.RequestType] = "REQUEST_TYPE",
			[ConditionAttributeTypes.ResponseTime] = "RESPONSE_TIME",
			[ConditionAttributeTypes.ResponseTimeClient] = "RESPONSE_TIME_CLIENT",
			[ConditionAttributeTypes.RmiClass] = "RMI_CLASS",
			[ConditionAttributeTypes.RmiMethod] = "RMI_METHOD",
			[ConditionAttributeTypes.ServiceDisplayName] = "SERVICE_DISPLAY_NAME",
			[ConditionAttributeTypes.ServiceName] = "SERVICE_NAME",
			[ConditionAttributeTypes.ServicePort] = "SERVICE_PORT",
			[ConditionAttributeTypes.ServicePublicDomainName] = "SERVICE_PUBLIC_DOMAIN_NAME",
			[ConditionAttributeTypes.ServiceRequestAttribute] = "SERVICE_REQUEST_ATTRIBUTE",
			[ConditionAttributeTypes.ServiceTag] = "SERVICE_TAG",
			[ConditionAttributeTypes.ServiceType] = "SERVICE_TYPE",
			[ConditionAttributeTypes.ServiceWebApplicationId] = "SERVICE_WEB_APPLICATION_ID",
			[ConditionAttributeTypes.ServiceWebContextRoot] = "SERVICE_WEB_CONTEXT_ROOT",
			[ConditionAttributeTypes.ServiceWebServerName] = "SERVICE_WEB_SERVER_NAME",
			[ConditionAttributeTypes.ServiceWebServiceName] = "SERVICE_WEB_SERVICE_NAME",
			[ConditionAttributeTypes.ServiceWebServiceNamespace] = "SERVICE_WEB_SERVICE_NAMESPACE",
			[ConditionAttributeTypes.SuspensionTime] = "SUSPENSION_TIME",
			[ConditionAttributeTypes.TotalProcessingTime] = "TOTAL_PROCESSING_TIME",
			[ConditionAttributeTypes.WaitTime] = "WAIT_TIME",
			[ConditionAttributeTypes.WebrequestQuery] = "WEBREQUEST_QUERY",
			[ConditionAttributeTypes.WebrequestRelativeUrl] = "WEBREQUEST_RELATIVE_URL",
			[ConditionAttributeTypes.WebrequestUrl] = "WEBREQUEST_URL",
			[ConditionAttributeTypes.WebrequestUrlHost] = "WEBREQUEST_URL_HOST",
			[ConditionAttributeTypes.WebrequestUrlPath] = "WEBREQUEST_URL_PATH",
			[ConditionAttributeTypes.WebrequestUrlPort] = "WEBREQUEST_URL_PORT",
			[ConditionAttributeTypes.WebserviceEndpoint] = "WEBSERVICE_ENDPOINT",
			[ConditionAttributeTypes.WebserviceMethod] = "WEBSERVICE_METHOD",
			[ConditionAttributeTypes.ZosCallType] = "ZOS_CALL_TYPE"
		};

		protected override Dictionary<ConditionAttributeTypes, string> Pairs => s_pairs;

		protected override string EntityString => "attribute";
	}
}
