using System.Collections.Generic;
using Dynatrace.Net.Environment.Events.Models;

namespace Dynatrace.Net.Common.Converters
{
	public class EventTypesConverter : JsonEnumConverter<EventTypes>
	{
		private static readonly Dictionary<EventTypes, string> s_pairs = new Dictionary<EventTypes, string>
		{
			[EventTypes.ApplicationJsFrameworkDetected] = "APPLICATION_JS_FRAMEWORK_DETECTED",
			[EventTypes.AvailabilityEvent] = "AVAILABILITY_EVENT",
			[EventTypes.ConnectionLost] = "CONNECTION_LOST",
			[EventTypes.CpuSaturated] = "CPU_SATURATED",
			[EventTypes.CustomAlert] = "CUSTOM_ALERT",
			[EventTypes.CustomAnnotation] = "CUSTOM_ANNOTATION",
			[EventTypes.CustomAppCrashRateIncreased] = "CUSTOM_APP_CRASH_RATE_INCREASED",
			[EventTypes.CustomConfiguration] = "CUSTOM_CONFIGURATION",
			[EventTypes.CustomDeployment] = "CUSTOM_DEPLOYMENT",
			[EventTypes.CustomInfo] = "CUSTOM_INFO",
			[EventTypes.DatabaseConnectionFailure] = "DATABASE_CONNECTION_FAILURE",
			[EventTypes.DeploymentChangedChange] = "DEPLOYMENT_CHANGED_CHANGE",
			[EventTypes.DeploymentChangedNew] = "DEPLOYMENT_CHANGED_NEW",
			[EventTypes.DeploymentChangedRemoved] = "DEPLOYMENT_CHANGED_REMOVED",
			[EventTypes.DockerMemorySaturation] = "DOCKER_MEMORY_SATURATION",
			[EventTypes.EbsVolumeHighLatency] = "EBS_VOLUME_HIGH_LATENCY",
			[EventTypes.ElasticLoadBalancerHighBackendFailureRate] = "ELASTIC_LOAD_BALANCER_HIGH_BACKEND_FAILURE_RATE",
			[EventTypes.ElasticLoadBalancerHighFailureRate] = "ELASTIC_LOAD_BALANCER_HIGH_FAILURE_RATE",
			[EventTypes.ElasticLoadBalancerHighUnhealthyHostRate] = "ELASTIC_LOAD_BALANCER_HIGH_UNHEALTHY_HOST_RATE",
			[EventTypes.ErrorEvent] = "ERROR_EVENT",
			[EventTypes.EsxiStart] = "ESXI_START",
			[EventTypes.FailureRateIncreased] = "FAILURE_RATE_INCREASED",
			[EventTypes.HighConnectivityFailures] = "HIGH_CONNECTIVITY_FAILURES",
			[EventTypes.HighDroppedPacketsRate] = "HIGH_DROPPED_PACKETS_RATE",
			[EventTypes.HighGcActivity] = "HIGH_GC_ACTIVITY",
			[EventTypes.HighLatency] = "HIGH_LATENCY",
			[EventTypes.HighNetworkErrorRate] = "HIGH_NETWORK_ERROR_RATE",
			[EventTypes.HighNetworkLossRate] = "HIGH_NETWORK_LOSS_RATE",
			[EventTypes.HighNetworkUtilization] = "HIGH_NETWORK_UTILIZATION",
			[EventTypes.HostConnectionFailed] = "HOST_CONNECTION_FAILED",
			[EventTypes.HostConnectionLost] = "HOST_CONNECTION_LOST",
			[EventTypes.HostDatastoreLowDiskSpace] = "HOST_DATASTORE_LOW_DISK_SPACE",
			[EventTypes.HostDiskLowInodes] = "HOST_DISK_LOW_INODES",
			[EventTypes.HostGracefullyShutdown] = "HOST_GRACEFULLY_SHUTDOWN",
			[EventTypes.HostLogAvailability] = "HOST_LOG_AVAILABILITY",
			[EventTypes.HostLogError] = "HOST_LOG_ERROR",
			[EventTypes.HostLogMatched] = "HOST_LOG_MATCHED",
			[EventTypes.HostLogPerformance] = "HOST_LOG_PERFORMANCE",
			[EventTypes.HostMaintenance] = "HOST_MAINTENANCE",
			[EventTypes.HostNoConnection] = "HOST_NO_CONNECTION",
			[EventTypes.HostOfServiceUnavailable] = "HOST_OF_SERVICE_UNAVAILABLE",
			[EventTypes.HostShutdown] = "HOST_SHUTDOWN",
			[EventTypes.HostTimeout] = "HOST_TIMEOUT",
			[EventTypes.HttpCheckGlobalOutage] = "HTTP_CHECK_GLOBAL_OUTAGE",
			[EventTypes.HttpCheckLocalOutage] = "HTTP_CHECK_LOCAL_OUTAGE",
			[EventTypes.HttpCheckTestLocationSlowdown] = "HTTP_CHECK_TEST_LOCATION_SLOWDOWN",
			[EventTypes.InsufficientDiskQueueDepth] = "INSUFFICIENT_DISK_QUEUE_DEPTH",
			[EventTypes.JavascriptErrorRateIncreased] = "JAVASCRIPT_ERROR_RATE_INCREASED",
			[EventTypes.LambdaFunctionHighErrorRate] = "LAMBDA_FUNCTION_HIGH_ERROR_RATE",
			[EventTypes.LogAvailability] = "LOG_AVAILABILITY",
			[EventTypes.LogError] = "LOG_ERROR",
			[EventTypes.LogMatched] = "LOG_MATCHED",
			[EventTypes.LogPerformance] = "LOG_PERFORMANCE",
			[EventTypes.LowDiskSpace] = "LOW_DISK_SPACE",
			[EventTypes.LowStorageSpace] = "LOW_STORAGE_SPACE",
			[EventTypes.MarkedForTermination] = "MARKED_FOR_TERMINATION",
			[EventTypes.MemoryResourcesExhausted] = "MEMORY_RESOURCES_EXHAUSTED",
			[EventTypes.MemorySaturated] = "MEMORY_SATURATED",
			[EventTypes.MobileAppCrashRateIncreased] = "MOBILE_APP_CRASH_RATE_INCREASED",
			[EventTypes.MonitoringUnavailable] = "MONITORING_UNAVAILABLE",
			[EventTypes.OpenstackKeystoneSlow] = "OPENSTACK_KEYSTONE_SLOW",
			[EventTypes.OpenstackKeystoneUnhealthy] = "OPENSTACK_KEYSTONE_UNHEALTHY",
			[EventTypes.OsiDockerDevicemapperLowDataSpace] = "OSI_DOCKER_DEVICEMAPPER_LOW_DATA_SPACE",
			[EventTypes.OsiDockerDevicemapperLowMetadataSpace] = "OSI_DOCKER_DEVICEMAPPER_LOW_METADATA_SPACE",
			[EventTypes.OverloadedStorage] = "OVERLOADED_STORAGE",
			[EventTypes.PerformanceEvent] = "PERFORMANCE_EVENT",
			[EventTypes.PgiCrashedInfo] = "PGI_CRASHED_INFO",
			[EventTypes.PgiHaproxyQueuedRequestsHigh] = "PGI_HAPROXY_QUEUED_REQUESTS_HIGH",
			[EventTypes.PgiHaproxySessionUsageHigh] = "PGI_HAPROXY_SESSION_USAGE_HIGH",
			[EventTypes.PgiMysqlSlowQueriesRateHigh] = "PGI_MYSQL_SLOW_QUERIES_RATE_HIGH",
			[EventTypes.PgiOfServiceUnavailable] = "PGI_OF_SERVICE_UNAVAILABLE",
			[EventTypes.PgiRmqHighFileDescUsage] = "PGI_RMQ_HIGH_FILE_DESC_USAGE",
			[EventTypes.PgiRmqHighMemUsage] = "PGI_RMQ_HIGH_MEM_USAGE",
			[EventTypes.PgiRmqHighProcessUsage] = "PGI_RMQ_HIGH_PROCESS_USAGE",
			[EventTypes.PgiRmqHighSocketsUsage] = "PGI_RMQ_HIGH_SOCKETS_USAGE",
			[EventTypes.PgiRmqLowDiskSpace] = "PGI_RMQ_LOW_DISK_SPACE",
			[EventTypes.ProcessCrashed] = "PROCESS_CRASHED",
			[EventTypes.ProcessCustomAvailability] = "PROCESS_CUSTOM_AVAILABILITY",
			[EventTypes.ProcessCustomError] = "PROCESS_CUSTOM_ERROR",
			[EventTypes.ProcessCustomPerformance] = "PROCESS_CUSTOM_PERFORMANCE",
			[EventTypes.ProcessGroupLowInstanceCount] = "PROCESS_GROUP_LOW_INSTANCE_COUNT",
			[EventTypes.ProcessLogAvailability] = "PROCESS_LOG_AVAILABILITY",
			[EventTypes.ProcessLogError] = "PROCESS_LOG_ERROR",
			[EventTypes.ProcessLogPerformance] = "PROCESS_LOG_PERFORMANCE",
			[EventTypes.ProcessRestart] = "PROCESS_RESTART",
			[EventTypes.ProcessUnavailable] = "PROCESS_UNAVAILABLE",
			[EventTypes.RdsOfServiceUnavailable] = "RDS_OF_SERVICE_UNAVAILABLE",
			[EventTypes.RdsRestartSequence] = "RDS_RESTART_SEQUENCE",
			[EventTypes.ResourceContention] = "RESOURCE_CONTENTION",
			[EventTypes.ServiceResponseTimeDegraded] = "SERVICE_RESPONSE_TIME_DEGRADED",
			[EventTypes.SlowDisk] = "SLOW_DISK",
			[EventTypes.SyntheticAvailability] = "SYNTHETIC_AVAILABILITY",
			[EventTypes.SyntheticNodeOutage] = "SYNTHETIC_NODE_OUTAGE",
			[EventTypes.SyntheticPrivateLocationOutage] = "SYNTHETIC_PRIVATE_LOCATION_OUTAGE",
			[EventTypes.SyntheticSlowdown] = "SYNTHETIC_SLOWDOWN",
			[EventTypes.ThreadsResourcesExhausted] = "THREADS_RESOURCES_EXHAUSTED",
			[EventTypes.UnexpectedHighLoad] = "UNEXPECTED_HIGH_LOAD",
			[EventTypes.UnexpectedLowLoad] = "UNEXPECTED_LOW_LOAD",
			[EventTypes.UserActionDurationDegradation] = "USER_ACTION_DURATION_DEGRADATION",
			[EventTypes.VirtualMachineShutdown] = "VIRTUAL_MACHINE_SHUTDOWN",
			[EventTypes.WebCheckGlobalOutage] = "WEB_CHECK_GLOBAL_OUTAGE",
			[EventTypes.WebCheckLocalOutage] = "WEB_CHECK_LOCAL_OUTAGE",
		};

		protected override Dictionary<EventTypes, string> Pairs { get; } = s_pairs;

		protected override string EntityString { get; } = "event type";
	}
}
