namespace Dynatrace.Net.Configuration.ManagementZones.Models
{
	public enum ComparisonBasicTypes
	{
		ApplicationType,
		AzureComputeMode,
		AzureSku,
		Bitness,
		CloudType,
		CustomApplicationType,
		DatabaseTopology,
		DcrumDecoderType,
		EntityId,
		HypervisorType,
		IndexedName,
		IndexedString,
		IndexedTag,
		Integer,
		IpAddress,
		MobilePlatform,
		OsArchitecture,
		OsType,
		PaasType,
		ServiceTopology,
		ServiceType,
		SimpleHostTech,
		SimpleTech,
		String,
		SyntheticEngineType,
		Tag
	}
}
