namespace Dynatrace.Net.Configuration.ManagementZones.Models
{
	public enum ManagementZoneRuleTypes
	{
		AppmonServer,
		AppmonSystemProfile,
		AwsAccount,
		AwsApplicationLoadBalancer,
		AwsAutoScalingGroup,
		AwsClassicLoadBalancer,
		AwsNetworkLoadBalancer,
		AwsRelationalDatabaseService,
		Azure,
		BrowserMonitor,
		CloudApplication,
		CloudApplicationNamespace,
		CloudFoundryFoundation,
		CustomApplication,
		CustomDevice,
		CustomDeviceGroup,
		DataCenterService,
		EnterpriseApplication,
		EsxiHost,
		ExternalMonitor,
		Host,
		HostGroup,
		HttpMonitor,
		KubernetesCluster,
		MobileApplication,
		OpenstackAccount,
		ProcessGroup,
		Service,
		WebApplication
	}
}
